version: "3.9"

services:
    app:
        image: node:18
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:3000
        command: bash -c "npm install && npx prisma generate && npm run build && npm run start:prod"
